// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_WY7tNdYtLrePxqbXs_v_ME2cUS3ndfg',
    appId: '1:587393372398:web:27a97c93b9cf1422cae3ff',
    messagingSenderId: '587393372398',
    projectId: 'cuny-connect',
    authDomain: 'cuny-connect.firebaseapp.com',
    databaseURL: 'https://cuny-connect-default-rtdb.firebaseio.com',
    storageBucket: 'cuny-connect.appspot.com',
    measurementId: 'G-D96DQM33S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Ub9fo7RI2TjvygjSdBZv56VWNTov0H4',
    appId: '1:587393372398:android:d7defcae8ea25a2acae3ff',
    messagingSenderId: '587393372398',
    projectId: 'cuny-connect',
    databaseURL: 'https://cuny-connect-default-rtdb.firebaseio.com',
    storageBucket: 'cuny-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEO2qc3qBAwpHJfFnCMYSvo50uA9hFVC4',
    appId: '1:587393372398:ios:86695a2a6ba78225cae3ff',
    messagingSenderId: '587393372398',
    projectId: 'cuny-connect',
    databaseURL: 'https://cuny-connect-default-rtdb.firebaseio.com',
    storageBucket: 'cuny-connect.appspot.com',
    iosBundleId: 'com.example.cunyConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEO2qc3qBAwpHJfFnCMYSvo50uA9hFVC4',
    appId: '1:587393372398:ios:a197cac853fa668fcae3ff',
    messagingSenderId: '587393372398',
    projectId: 'cuny-connect',
    databaseURL: 'https://cuny-connect-default-rtdb.firebaseio.com',
    storageBucket: 'cuny-connect.appspot.com',
    iosBundleId: 'com.example.cunyConnect.RunnerTests',
  );
}
